[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && npm install --build-from-source"

[deploy]
startCommand = "cd backend && node src/utils/seeder.js && node server.js"
restartPolicyType = "always"
